### ISSUE TITLE
Adjust typography and spacing

### ISSUE THREAD

**Issue by hasanhaja** [hasanhaja/site#34]
## Todo

- [ ] Consider using `clamp` for hero text for a more responsive font size. eg `clamp(7rem, Xvw, 12rem);`
- [ ] What is the best way to layout text based content that consists of lists
- [ ] Set paragraph margin for last of type/child
- [ ] https://www.youtube.com/shorts/wcLPloA1dSs
- [ ] https://piccalil.li/
- [ ] https://dylanatsmith.com/wrote/styling-the-kbd-element
